// <auto-generated />
using System;
using LearningPlatformRepoPattern.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearningPlatformRepoPattern.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260906112950_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LearningPlatformRepoPattern.Models.MasterCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CourseName");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("createdBy");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mstatus");

                    b.Property<string>("ThumbnailPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mthumbnail");

                    b.HasKey("Id");

                    b.ToTable("Master_course");
                });

            modelBuilder.Entity("LearningPlatformRepoPattern.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("material_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Assignment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("assignment");

                    b.Property<int>("MasterCourseId")
                        .HasColumnType("int")
                        .HasColumnName("mid");

                    b.Property<int>("SubCourseId")
                        .HasColumnType("int")
                        .HasColumnName("sid");

                    b.Property<int>("TopicId")
                        .HasColumnType("int")
                        .HasColumnName("tid");

                    b.HasKey("Id");

                    b.HasIndex("MasterCourseId");

                    b.HasIndex("SubCourseId");

                    b.HasIndex("TopicId");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("LearningPlatformRepoPattern.Models.Mcq", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("mcq_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("answer");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int")
                        .HasColumnName("material_id");

                    b.Property<string>("Option1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("option1");

                    b.Property<string>("Option2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("option2");

                    b.Property<string>("Option3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("option3");

                    b.Property<string>("Option4")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("option4");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.ToTable("Mcq");
                });

            modelBuilder.Entity("LearningPlatformRepoPattern.Models.SubCourse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(9, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("samount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdAt");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("createdBy");

                    b.Property<int>("MasterCourseId")
                        .HasColumnType("int")
                        .HasColumnName("mid");

                    b.Property<int?>("MasterCourseId1")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sstatus");

                    b.Property<string>("SubCourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SubCourseName");

                    b.HasKey("Id");

                    b.HasIndex("MasterCourseId");

                    b.HasIndex("MasterCourseId1");

                    b.ToTable("sub_course");
                });

            modelBuilder.Entity("LearningPlatformRepoPattern.Models.Topic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MasterCourseId")
                        .HasColumnType("int")
                        .HasColumnName("mid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tstatus");

                    b.Property<int>("SubCourseId")
                        .HasColumnType("int")
                        .HasColumnName("sid");

                    b.Property<string>("ThumbnailPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tthumbnail");

                    b.Property<string>("TopicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tname");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("videoUrl");

                    b.HasKey("Id");

                    b.HasIndex("MasterCourseId");

                    b.HasIndex("SubCourseId");

                    b.ToTable("Topic");
                });

            modelBuilder.Entity("LearningPlatformRepoPattern.Models.TopicProgress", b =>
                {
                    b.Property<int>("ProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ProgressId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgressId"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<bool>("McqPassed")
                        .HasColumnType("bit")
                        .HasColumnName("mcq_passed");

                    b.Property<int>("Sid")
                        .HasColumnType("int")
                        .HasColumnName("sid");

                    b.Property<int>("Tid")
                        .HasColumnType("int")
                        .HasColumnName("tid");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("ProgressId");

                    b.ToTable("TopicProgress");
                });

            modelBuilder.Entity("LearningPlatformRepoPattern.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_email");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_name");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_password");

                    b.HasKey("UserId");

                    b.ToTable("user");
                });

            modelBuilder.Entity("LearningPlatformRepoPattern.Models.my_courses", b =>
                {
                    b.Property<int>("mcid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("mcid"));

                    b.Property<int>("Sid")
                        .HasColumnType("int")
                        .HasColumnName("sid");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("mcid");

                    b.HasIndex("Sid");

                    b.HasIndex("UserId");

                    b.ToTable("my_courses");
                });

            modelBuilder.Entity("LearningPlatformRepoPattern.Models.Material", b =>
                {
                    b.HasOne("LearningPlatformRepoPattern.Models.MasterCourse", "MasterCourse")
                        .WithMany()
                        .HasForeignKey("MasterCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearningPlatformRepoPattern.Models.SubCourse", "SubCourse")
                        .WithMany()
                        .HasForeignKey("SubCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearningPlatformRepoPattern.Models.Topic", "Topic")
                        .WithMany("Materials")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MasterCourse");

                    b.Navigation("SubCourse");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("LearningPlatformRepoPattern.Models.Mcq", b =>
                {
                    b.HasOne("LearningPlatformRepoPattern.Models.Material", "Material")
                        .WithMany("Mcqs")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("LearningPlatformRepoPattern.Models.SubCourse", b =>
                {
                    b.HasOne("LearningPlatformRepoPattern.Models.MasterCourse", "MasterCourse")
                        .WithMany()
                        .HasForeignKey("MasterCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearningPlatformRepoPattern.Models.MasterCourse", null)
                        .WithMany("SubCourses")
                        .HasForeignKey("MasterCourseId1");

                    b.Navigation("MasterCourse");
                });

            modelBuilder.Entity("LearningPlatformRepoPattern.Models.Topic", b =>
                {
                    b.HasOne("LearningPlatformRepoPattern.Models.MasterCourse", "MasterCourse")
                        .WithMany()
                        .HasForeignKey("MasterCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearningPlatformRepoPattern.Models.SubCourse", "SubCourse")
                        .WithMany()
                        .HasForeignKey("SubCourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MasterCourse");

                    b.Navigation("SubCourse");
                });

            modelBuilder.Entity("LearningPlatformRepoPattern.Models.my_courses", b =>
                {
                    b.HasOne("LearningPlatformRepoPattern.Models.SubCourse", null)
                        .WithMany()
                        .HasForeignKey("Sid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearningPlatformRepoPattern.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("LearningPlatformRepoPattern.Models.MasterCourse", b =>
                {
                    b.Navigation("SubCourses");
                });

            modelBuilder.Entity("LearningPlatformRepoPattern.Models.Material", b =>
                {
                    b.Navigation("Mcqs");
                });

            modelBuilder.Entity("LearningPlatformRepoPattern.Models.Topic", b =>
                {
                    b.Navigation("Materials");
                });
#pragma warning restore 612, 618
        }
    }
}
